version: '2'
services:
  homeBackend:
      image: java:8
      container_name: oj_backend
      ports:
        - 8080:8080
      volumes:
        - ./backend:/home/app/oj
      command: sh -c "cd /home/app/oj && ./gradlew build && java -jar build/libs/backend.jar"
      networks:
        main:
          aliases:
            - ojBackend

  homeWeb:
      image: node:8-alpine
      container_name: oj_web
      ports:
        - 3000:3000
      volumes:
        - ./web:/home/app/oj
      command: sh -c "cd /home/app/oj && npm i && npm start"
      links:
        - ojBackend
      networks:
        main:
          aliases:
            - ojWeb
networks:
  main: