version: '2'
services:
  ojBackend:
      image: java:8
      container_name: oj_backend
      ports:
        - 8082:8080
      volumes:
        - ./backend/:/home/app/oj/backend
      command: sh -c "cd /home/app/oj/backend/ && ./gradlew clean build && java -jar build/libs/backend.jar"
      networks:
        main:
          aliases:
            - ojBackend

  ojWeb:
      image: node:8-alpine
      container_name: oj_web
      ports:
        - 3000:3000
      volumes:
        - ./web:/home/app/oj
      command: sh -c "cd /home/app/oj && npm i && npm start"
      links:
        - ojBackend
      networks:
        main:
          aliases:
            - ojWeb
  mysql:
      image: mysql:5.7
      restart: unless-stopped
      container_name: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: wap3gqqcom
      volumes:
        - /var/lib/mysql57-data:/var/lib/mysql
networks:
  main: